### ISSUE TITLE
Confused on how to represent links as rigid groups

### ISSUE THREAD

**Issue by NicoPowers** [Roboy/SDFusion#6]
Hello,

I am very confused on the idea of using a rigid group to represent my links. I simply have components that represent my links, and therefore I cannot have a rigid group of only 1 components, as that would not be a group, so I am not sure how I am supposed to convert each component to their respective rigid group.

I am trying to do this for a very simple 2WD robot:
![image](https://user-images.githubusercontent.com/24234144/149687097-48f7c95f-5a60-4ab3-a8ff-562e7c35ab48.png)

But if I create a rigid group from all the links, it will only generate 1 link; which makes sense since a rigid group represents a link, but how would I go about creating 4 rigid groups for 4 of my links (I should end up with 4 links, left wheel, right wheel, body, and caster)?

It would be nice to see an actual example with Fusion 360 to clear this up, or perhaps a video showing a quick demo. 

Thanks.

**Comment by missxa** [comment]
You need at least 2 components for each link, as there's no alternative way to create a rigid body, which is then exported as a link. Feel free to add a PR if you find a workaround :)

**Comment by vacoff** [comment]
I also got this problem, was very confused on first time. The quick video would be very nice
